### ISSUE TITLE
Compatability Issue With CelesteNet

### ISSUE THREAD

**Issue by Catandcomparator** [CommunalHelper/AdventureHelper#3]
If celestenet is enabled and you are connected, other players are able to activate the pressure buttons.

The issue is shown in https://youtu.be/IiTLdmSZHNI. Watch the button and the piston it is connected to.

Edit: Oops, i followed a link on factoryhelper page to wrong issues area. My mistake!

Edit: I'm not sure about last edit so i'm undoing it. Sorry!

**Comment by bigkahuna443** [comment]
Closing, does not apply to this helper.

**Comment by Catandcomparator** [comment]
Sorry!
